name: contact
description: "A Flutter Test Case Project Written By Arif Emre Ankara"

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  global:
    path: feature/global
  core:
    path: module/core
  uikit:
    path: module/uikit
  welcome:
    path: feature/welcome
  contacts:
    path: feature/contacts
  
  
  packages:
    path: module/packages
  

  cupertino_icons: ^1.0.8
  easy_localization: ^3.0.7
  envied: ^1.0.0
  go_router: ^14.6.2
  sliver_tools: ^0.2.12
  get_it: ^8.0.2
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.16

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  envied_generator: ^1.0.0
  build_runner: ^2.4.13

flutter_launcher_icons:
  ios: true
  image_path: "assets/images/ios_appicon.png"
  remove_alpha_ios: true

flutter_gen:
  assets:
    outputs:
      package_parameter_enabled: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/translations/